# Generated by Django 3.2.9 on 2021-11-11 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('humanpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
