# Generated by Django 3.2.9 on 2021-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanpro', '0002_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
