# Generated by Django 3.2.9 on 2021-11-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanpro', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
