# Generated by Django 3.2.9 on 2021-11-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanpro', '0004_remove_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('STD', 'base employee'), ('MGR', 'manager'), ('SUP', 'supervisor'), ('PRE', 'president')], default='STD', max_length=3),
        ),
    ]
